#!/usr/bin/env python3
"""Generate platform-specific style assets from the canonical tokens."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
TOKENS_PATH = ROOT / "tokens" / "tokens.json"


def get_path(tokens: dict, path: str) -> Any:
    value: Any = tokens
    for part in path.split("."):
        value = value[part]
    return value


def resolve_tokens(tokens: dict) -> dict:
    def resolve(value: Any, references: tuple[str, ...] = ()) -> Any:
        if isinstance(value, str) and value.startswith("{") and value.endswith("}"):
            path = value[1:-1]
            if path in references:
                raise ValueError(f"Circular token reference: {' -> '.join((*references, path))}")
            return resolve(get_path(tokens, path), (*references, path))
        if isinstance(value, dict):
            return {name: resolve(item, references) for name, item in value.items()}
        if isinstance(value, list):
            return [resolve(item, references) for item in value]
        return value

    return resolve(tokens)


def load_tokens() -> dict:
    raw_tokens = json.loads(TOKENS_PATH.read_text(encoding="utf-8"))
    return resolve_tokens(raw_tokens)


def scss_name(name: str) -> str:
    return name.replace("_", "-")


def render_scss(tokens: dict) -> str:
    lines = ["// Generated by scripts/generate.py. Do not edit.", ""]
    for group in ("neutral", "brand", "dark-mode", "interface"):
        lines.append(f"// {group.title()}")
        for name, value in tokens["colors"][group].items():
            prefix = "dark-mode-" if group == "dark-mode" else ""
            lines.append(f"$eeca-{prefix}{scss_name(name)}: {value};")
        lines.append("")

    for name, values in tokens["palettes"].items():
        lines.append(f"$eeca-palette-{scss_name(name)}: ({', '.join(values)});")

    web_font = ", ".join(f'"{name}"' if " " in name else name for name in tokens["typography"]["platforms"]["web"])
    lines.extend(
        [
            "",
            f"$eeca-font-family-web: {web_font};",
            f"$eeca-font-weight-regular: {tokens['typography']['weights']['regular']};",
            f"$eeca-font-weight-medium: {tokens['typography']['weights']['medium']};",
            f"$eeca-font-weight-bold: {tokens['typography']['weights']['bold']};",
            f"$eeca-corner-radius: {tokens['shape']['corner-radius-px']}px;",
            "",
        ]
    )
    return "\n".join(lines)


def render_css(tokens: dict) -> str:
    lines = ["/* Generated by scripts/generate.py. Do not edit. */", ":root {"]
    for group in ("neutral", "brand", "dark-mode", "interface"):
        for name, value in tokens["colors"][group].items():
            prefix = "dark-mode-" if group == "dark-mode" else ""
            lines.append(f"  --eeca-{prefix}{scss_name(name)}: {value};")

    web_font = ", ".join(f'"{name}"' if " " in name else name for name in tokens["typography"]["platforms"]["web"])
    lines.extend(
        [
            f"  --eeca-font-family-web: {web_font};",
            f"  --eeca-font-weight-regular: {tokens['typography']['weights']['regular']};",
            f"  --eeca-font-weight-medium: {tokens['typography']['weights']['medium']};",
            f"  --eeca-font-weight-bold: {tokens['typography']['weights']['bold']};",
            f"  --eeca-corner-radius: {tokens['shape']['corner-radius-px']}px;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_python(tokens: dict) -> str:
    colors = {
        (f"dark-mode-{name}" if group_name == "dark-mode" else name): value
        for group_name, group in tokens["colors"].items()
        for name, value in group.items()
    }
    plotly_layout = {
        "colorway": tokens["palettes"]["categorical"],
        "font": {
            "color": tokens["colors"]["interface"]["text"],
            "family": ", ".join(tokens["typography"]["platforms"]["charts"]),
            "size": tokens["typography"]["sizes-px"]["chart"],
        },
        "paper_bgcolor": tokens["colors"]["interface"]["surface"],
        "plot_bgcolor": tokens["colors"]["interface"]["surface"],
    }
    return "\n".join(
        [
            '"""Generated EECA data visualisation tokens. Do not edit."""',
            "",
            f"COLORS = {colors!r}",
            f"PALETTES = {tokens['palettes']!r}",
            f"FONTS = {tokens['typography']['platforms']!r}",
            f"PLOTLY_LAYOUT = {plotly_layout!r}",
            "",
        ]
    )


def databricks_theme(tokens: dict) -> dict:
    typography = tokens["typography"]
    font_family = typography["platforms"]["databricks"][0]
    theme = dict(tokens["platforms"]["databricks"]["theme"])
    font_color = theme["fontColor"]
    font_settings = {
        role: {
            "fontFamily": font_family,
            "fontSize": settings["size-px"],
            "fontWeight": settings["weight"],
        }
        for role, settings in typography["databricks-roles"].items()
    }
    for role in ("base", "fieldTitle", "fieldValue"):
        font_settings[role]["fontColor"] = font_color

    theme["visualizationColors"] = tokens["palettes"]["categorical"]
    theme["fontSettings"] = font_settings
    theme["fontFamily"] = font_family
    return theme


def outputs(tokens: dict) -> dict[Path, str]:
    json_text = json.dumps(tokens, indent=2) + "\n"
    databricks_text = json.dumps(databricks_theme(tokens), indent=2) + "\n"
    return {
        ROOT / "dist" / "scss" / "_tokens.scss": render_scss(tokens),
        ROOT / "dist" / "css" / "tokens.css": render_css(tokens),
        ROOT / "dist" / "python" / "eeca_visualisation_styles.py": render_python(tokens),
        ROOT / "dist" / "json" / "tokens.json": json_text,
        ROOT / "dist" / "json" / "databricks-dashboard-theme.json": databricks_text,
    }


def generate(check: bool = False) -> bool:
    valid = True
    for path, content in outputs(load_tokens()).items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"Out of date: {path.relative_to(ROOT)}")
                valid = False
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Generated {path.relative_to(ROOT)}")
    return valid


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    return 0 if generate(check=args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
